gui:
  theme:
    activeBorderColor:
      - "#f38ba9"
      - bold
    inactiveBorderColor:
      - "#3b3e4a"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#ffffff"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"
  nerdFontsVersion: "3"
  border: single
git:
  log:
    showWholeGraph: true
